name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: cd UniSim && ./gradlew build jacocoTestReport
    - name: upload JaCoco coverage report
      uses: actions/upload-artifact@v4.4.3
      with:
        name: jacoco-report
        path: UniSim/headless/build/reports/jacoco/test/html/
    - name: upload JAR
      uses: actions/upload-artifact@v4.4.3
      with:
        name: unisim.jar
        path: UniSim/lwjgl3/build/libs/unisim.jar

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        build-root-directory: UniSim

  release:
    runs-on: ubuntu-22.04
    needs: [ "build" ]
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
    - name: Download Ubuntu Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: unisim.jar
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: unisim.jar
